server:
  port: 8080

cloud:
  aws:
    region:
      static: ${AWS_RE}
    stack:
      auto: false

---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

custom:
  jwt:
    secretKey : ${JWT_SECRET_KEY}

---

springdoc:
  packages-to-scan: com.colabear754.springdoc_example.controllers
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

---
spring:
  main:
    web-application-type: servlet

---
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
            scope:
              - user:email
              - read:user
kakao:
  key:
    client-id: ${KAKAO_REST_API}
    redirect-url: ${KAKAO_REDIRECT_URL}

---
app:
  auth:
    token:
      refresh-cookie-key: ${REFRESH_COOKIE_KEY}

---

logging:
  level:
    com.supernova.lymming: info

---
spring:
  main:
    allow-bean-definition-overriding: true